import { useSession } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { z } from "zod";

import {
  Dialog,
  DialogContent,
  DialogTrigger
} from "~/ui/dialog";
import { api } from "~/utils/api";
import { useZodForm } from "~/utils/zod-form";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-800">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {hello.data?.greeting}
          <FAQForm />
          <Dialog>
            <DialogTrigger>Open</DialogTrigger>
            <DialogContent>
              <FAQForm />
            </DialogContent>
          </Dialog>
        </div>
      </main>
    </>
  );
};

export const FAQFormSchema = z.object({
  question: z.string().min(3),
  answer: z.string().min(5),
});

function FAQForm() {
  const { isSignedIn } = useSession();

  const methods = useZodForm({
    schema: FAQFormSchema,
  });

  const utils = api.useContext();
  const createFAQ = api.faq.create.useMutation({
    onSettled: async () => {
      await utils.faq.invalidate();
      methods.reset();
    },
  });

  const onSubmit = methods.handleSubmit(
    (data) => {
      createFAQ.mutate(data);
    },
    (e) => {
      console.log("Whoops... something went wrong!");
      console.error(e);
    }
  );

  return (
    <div className="mx-auto max-w-xl space-y-8">
      <form action="" className="flex flex-col gap-4" onSubmit={void onSubmit}>
        <div className="space-y-1">
          <label htmlFor="name">Title</label>
          <textarea
            id="name"
            className="bg-slate-800"
            {...methods.register("question")}
          />
          <p className="font-medium text-red-500">
            {methods.formState.errors?.question?.message}
          </p>
        </div>
        <div className="space-y-1">
          <label htmlFor="text">Body</label>
          <textarea
            id="text"
            className="bg-slate-800"
            {...methods.register("answer")}
          />
          <p className="font-medium text-red-500">
            {methods.formState.errors?.answer?.message}
          </p>
        </div>

        <button type="submit" disabled={!isSignedIn}>
          {!isSignedIn
            ? "Sign in to Post"
            : createFAQ.isLoading
            ? "Loading..."
            : "Post"}
        </button>
        <p className="font-medium text-red-500">{createFAQ.error?.message}</p>
      </form>
    </div>
  );
}
export default Home;
